name: Malawi Life
favicon: null
layout_spectrum: 0.9881726643070579
typography_spectrum: 0.5920209607575089
title: Malawi Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.22113888314925134
  lightness: 0.14346920978277922
  saturation: 0.7011698696296662
  rhythmicContrast: 0.8932588587049395
purpose: []
